### PR TITLE
Python Question - Lambda

### PR DESCRIPTION
**Pull request by austinsonger**
Added answer to the Python question related to Lambda.

### CODE REVIEW

**Comment by surister** [comment]
Hi, thanks for contributing. About your second commit, we were just working about it in #64  :P

**Comment by bregman-arie** [comment]
Thanks for adding all these answers

**Comment by austinsonger** [comment]
I deleted a duplicate question so the total amount of questions should be updated.

**Comment by surister** [comment]
It might be a subject worth discussing over a new issue

**Pull request merged**
