### PR TITLE
Add Subject Icons + some typos

### PR DESCRIPTION
**Pull request by renatocfrancisco**
sorry for the amount of commits
i kinda like this repo.

### CODE REVIEW

**Comment by renatocfrancisco** [comment]
can you see the .png files?
is there a problem for a request with many commits? (sorry)

**Comment by bregman-arie** [comment]
@renatocfrancisco I can see the .png files. They are great. I'm not sure where you got them from but if needed, please add proper credit for them in credits.md (I'll wait for your confirmation before merging)

Regarding the number of commits, if possible please squash them. If that's somewhat challenging, I guess we can skip it this time:)  but I would say at least try to. It's not that complex. You can make a copy of the repo and give it a try before doing it on the original repository.

And thanks for changes. It's great.

**Comment by renatocfrancisco** [comment]
can i redo the entire pull request?
i don't even know "squash merge"
i will add credits for the google and virtual box logo.

**Comment by bregman-arie** [comment]
Sure

**Comment by renatocfrancisco** [comment]
seriously, idk how to merge commit

**Pull request closed without merging**
