### PR TITLE
Adds github actions

### PR DESCRIPTION
**Pull request by apoorva-saxena**
Adds the github actions to the project

### CODE REVIEW

**Comment by bregman-arie** [comment]
Adding CI is a good idea but, let's run perhaps the scripts in the `scripts` directory and not a demo. WDYT?

**Comment by apoorva-saxena** [comment]
> Adding CI is a good idea but, let's run perhaps the scripts in the `scripts` directory and not a demo. WDYT?

makes sense, have updated accordingly. :)

**Comment by bregman-arie** [comment]
I still see the demo: https://github.com/bregman-arie/devops-exercises/pull/171/files
You probably need to rebase your changes.

**Comment by bregman-arie** [comment]
Was covered by another PR

**Comment by bregman-arie** [comment]
Was covered by another PR

**Pull request closed without merging**
