### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by Brendon127**

### CODE REVIEW

**Comment by bregman-arie** [comment]
why "Explain stateless vs. stateful" needs a question mark?
If it was "Can you Explain stateless vs. stateful?" I understand but why the first form requires a question mark?

**Comment by Brendon127** [comment]
> why "Explain stateless vs. stateful" needs a question mark?
> If it was "Can you Explain stateless vs. stateful?" I understand but why the first form requires a question mark?

You are right. The first form is correct, indirect questions do not get question marks. I'll change it back to the first form.

**Comment by bregman-arie** [comment]
Thanks for the effort but I still see question marks where it shouldn't be. Like here:

"Describe the workflow of setting up some type of web server?"

**Comment by bregman-arie** [comment]
Accidently closed it. See my comment above.

**Comment by Brendon127** [comment]
I removed all the changes to question marks. Only the spelling fixes are included now.

**Pull request merged**
