### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akshayamadhuri**
issue : #10214

### CODE REVIEW

**Review by andrzejsydor — APPROVED** [review]

**Comment by gkarthiks** [comment]
I like the crisp response, but there's a little detail that needs to be added I believe. 

If the kubelet on a node is stopped, the pods on that nodes will not be terminated effective immediately. The containers will continue to run, but since the health probes are not executed and reporting via PLEG is not available for the api-server, the API Server reckons the node and pods are not healthy and marks it for termination. But can't do that as well, since the kublet is down even if the control plane marks pods on that node for termination, the deletions cannot be enforced since kubelet is not running

So if kubelet is down, the pods on that node will become unmanaged orphans that continue running though they are "deleted" from Kubernetes' perspective. They won't get cleaned up until the kubelet is revived or the node is drained/decommissioned or naturally the containers' process exits out of error or completed status.

**Comment by akshayamadhuri** [comment]
@gkarthiks  shall I add more content

**Comment by gkarthiks** [comment]
@akshayamadhuri I would suggest that, but upto maintainers

**Comment by bregman-arie** [comment]
@akshayamadhuri Feel free

**Review by andrzejsydor — APPROVED** [review]

**Pull request closed without merging**
