### PR TITLE
ANSWERED Network Related

### PR DESCRIPTION
**Pull request by austinsonger**

### CODE REVIEW

**Comment by bregman-arie** [comment]
Thanks, this is great. One comment about TCP vs. UDP: "UDP is faster, simpler and more efficient than TCP" - it should be mentioned they are used for different use cases and UDP is less reliable.

**Comment by austinsonger** [comment]
I actually don't like this question. Because it depends on what you need done. I was going to delete it, because this is an extremely subjective question.

**Comment by bregman-arie** [comment]
I'm fine with removing it

**Comment by surister** [comment]
Maybe turn it into: "What are the differences between UDP and TCP" ?

**Comment by bregman-arie** [comment]
We already have such a question. Removing it should be fine.

**Pull request merged**
