### PR TITLE
SQL Questions and Answers

### PR DESCRIPTION
**Pull request by AbdulKhadhar**
Beginners and Intermediate level SQL questions

### CODE REVIEW

**Comment by bregman-arie** [comment]
Is it taken from somewhere or did you write it?
Also, it's not adjusted to the format used right now

**Review by bregman-arie — CHANGES_REQUESTED** [review]
It's not the format used right now + it should be added under SQL section.

**Comment by AbdulKhadhar** [comment]
> 
> 
> It's not the format used right now + it should be added under SQL section.

Where I have to contribute it ? CONTRIBUTING.md or somewhere else ?

**Comment by zdj21jdz** [comment]
Hey @AbdulKhadhar ,

You can add the additional SQL questions under README.md - you can check to see the format of how I wrote my SQL questions, and how you can add to them. Let me know if you have any questions!

PS - These are really good SQL questions!

**Pull request closed without merging**
