### PR TITLE
Add new Perl questions

### PR DESCRIPTION
**Pull request by adrianfusco**
New perl topic and questions added

### CODE REVIEW

**Review by bregman-arie — CHANGES_REQUESTED** [review]
Good stuff. My only comment would be to push the <td>Perl</td> to the last row of the table because each row has 6 cells and with this change one of them will be with 7, which looks odd.

**Review by bregman-arie — CHANGES_REQUESTED** [review]
Good stuff. My only comment would be to push the <td>Perl</td> to the last row of the table because each row has 6 cells and with this change one of them will be with 7, which looks odd.

**Comment by adrianfusco** [comment]
Oh, you're right Arie. Sorry for the mistake.

Fixed with the new commit.

**Comment by bregman-arie** [comment]
Looks good! Thank you :)

**Pull request merged**
