### PR TITLE
Feature/new perl regex questions and answers

### PR DESCRIPTION
**Pull request by adrianfusco**

### CODE REVIEW

**Comment by bregman-arie** [comment]
Nice. I think we might want to have a whole separate section for regular expression exercises, but that's for a another commit.

**Comment by adrianfusco** [comment]
How do you think is the best way to do it? Create a new `perl` folder in the `exercises` directory and:

1. Move the whole Perl section
2. Move just the Perl regex section

**Comment by bregman-arie** [comment]
> How do you think is the best way to do it? Create a new `perl` folder in the `exercises` directory and:
> 
> 1. Move the whole Perl section
> 2. Move just the Perl regex section and create a table in the main perl README

Perl section should move entirely to exercises/perl/README.md as it will be done for all the other sections.
What I was thinking about regex is to create exercises/regex/README.md and combine all the regex questions there from all the different sections (Perl, Python, ...). What do you think? or is it better to have separate regex questions for each programming language? I'm open to any idea at this point

**Comment by adrianfusco** [comment]
> > How do you think is the best way to do it? Create a new `perl` folder in the `exercises` directory and:
> > 
> > 1. Move the whole Perl section
> > 2. Move just the Perl regex section and create a table in the main perl README
> 
> Perl section should move entirely to exercises/perl/README.md as it will be done for all the other sections. What I was thinking about regex is to create exercises/regex/README.md and combine all the regex questions there from all the different sections (Perl, Python, ...). What do you think? or is it better to have separate regex questions for each programming language? I'm open to any idea at this point

Perfect, I'll move the whole section then. It will be better.

I think it's better to have separated regex sections for every language. Python does not have all the features of the `PCRE` and there are differences using the `re` module.

[Regular expressions in Python and Perl](https://www.johndcook.com/blog/python_regex/)

Let me know what do you think about and we can make the change as you think it's better.

**Comment by bregman-arie** [comment]
> > > How do you think is the best way to do it? Create a new `perl` folder in the `exercises` directory and:
> > > 
> > > 1. Move the whole Perl section
> > > 2. Move just the Perl regex section and create a table in the main perl README
> > 
> > 
> > Perl section should move entirely to exercises/perl/README.md as it will be done for all the other sections. What I was thinking about regex is to create exercises/regex/README.md and combine all the regex questions there from all the different sections (Perl, Python, ...). What do you think? or is it better to have separate regex questions for each programming language? I'm open to any idea at this point
> 
> Perfect, I'll move the whole section then. It will be better.
> 
> I think it's better to have separated regex sections for every language. Python does not have all the features of the `PCRE` and there are differences using the `re` module.
> 
> [Regular expressions in Python and Perl](https://www.johndcook.com/blog/python_regex/)
> 
> Let me know what do you think about and we can make the change as you think it's better.

Sounds good to me. Let's then move Perl to the exercises directory and keep the regex sections separated.

**Comment by adrianfusco** [comment]
> Sounds good to me. Let's then move Perl to the exercises directory and keep the regex sections separated.

Perfect. I'll do the change.

Tyvm!

**Pull request merged**
