### PR TITLE
added answer under Python/What is lambda? How ..

### PR DESCRIPTION
**Pull request by sagorbrur**
Hi,
I have added answer under `Python/What is lambda? How is it use?`
Please check, if possible please add.

regards
Sagor

### CODE REVIEW

**Comment by surister** [comment]
I will merge and edit it to:

A <code>lambda</code> expression is an 'anonymous' function, the differnce between a normal defined function using the keyword `def`` is the syntax and ussage. </br>

The syntax is:
` labmda [parameters]: [expresion]`

**Examples:**

1. A lambda function add 10 with any argument passed.

```py
x = lambda a: a + 10
print(x(10))
```

2. An addition function

```py
addition = lambda x, y: x + y
print(addition(10, 20))
```

3. Squaring function

```py
square = lambda x : x ** 2
print(square(5))
```

Generally it is considered a bad practice under PEP 8 to asign a lambda expresion, they are meant to be used as parameters and inside of other defined functions.

**Comment by sagorbrur** [comment]
Hi @surister 
Please do edit according  to your suggestion and merge. 
thanks and regards
Sagor

**Comment by sagorbrur** [comment]
thanks. 
that merged answer was perfect.
so, I am closing this.
regards
Sagor

**Comment by surister** [comment]
I liked more your answer with my fixes since the one that was merged is a bit incomplete, will probably change this down the line, feel free to reopen the pr with my suggestion if you want. @sagorbrur

**Comment by sagorbrur** [comment]
Hi @surister 
thanks. Okay, I will reopen the pr with your suggestion.
regards

**Pull request closed without merging**
