### PR TITLE
Add definitions for SLI, SLO, SLA, error budget and toil

### PR DESCRIPTION
**Pull request by ronan-s1**
Some info was taken from: https://sre.google/sre-book/table-of-contents/

### CODE REVIEW

**Comment by ronan-s1** [comment]
> Please add credit as part of the answer

Added a Credits section

**Comment by bregman-arie** [comment]
Inside the answer, not under the header. Thanks

**Comment by ronan-s1** [comment]
> Inside the answer, not under the header. Thanks

Done

**Comment by ronan-s1** [comment]
@bregman-arie Bump

**Pull request merged**
