### PR TITLE
answered questions 

### PR DESCRIPTION
**Pull request by deveshgoyal1000**

### CODE REVIEW

**Comment by bregman-arie** [comment]
Looks like the answers are copied. For example, the open source answer is definitely copied from techtarget. In that case, please provide attribution. Thanks.

**Comment by deveshgoyal1000** [comment]
should I provide sources?


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by bregman-arie** [comment]
Yes

**Comment by deveshgoyal1000** [comment]
ohk where to mention them below the answers or where

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Comment by bregman-arie** [comment]
> ohk where to mention them below the answers or where
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Tags:** Reusable

Whatever you prefer. You have a couple of examples in the repository.

**Comment by deveshgoyal1000** [comment]
ok

**Pull request closed without merging**
